# This file stores configurations for your Shopify app.
name = "control-tower"
client_id = "4a14d7f9a2aa6a560d71afeb29f4cbb6"
application_url = "https://control-tower-2.myshopify.com/"
embedded = true
handle = "control-tower-app"

[access_scopes]
scopes = "write_products, read_products, read_orders, write_orders, read_customers, read_inventory, read_locations, read_analytics, read_reports, read_fulfillments, read_shipping, read_discounts, read_price_rules, read_marketing_events"

[auth]
redirect_urls = [
  "https://control-tower-2.myshopify.com/auth/callback",
  "https://control-tower-2.myshopify.com/auth/shopify/callback",
  "https://control-tower-2.myshopify.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[build]
automatically_update_urls_on_dev = true
