# This file stores configurations for your Shopify app.
name = "control-tower"
client_id = "4a14d7f9a2aa6a560d71afeb29f4cbb6"
application_url = "https://control-tower-2.myshopify.com/"
embedded = true
handle = "control-tower-app"

[access_scopes]
scopes = "write_products, read_orders"

[auth]
redirect_urls = [
  "https://control-tower-2.myshopify.com/auth/callback",
  "https://control-tower-2.myshopify.com/auth/shopify/callback",
  "https://control-tower-2.myshopify.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "pubsub://shop-webhooks:control-tower"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/webhooks/app/order-create"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/webhooks/aws"

[build]
automatically_update_urls_on_dev = true
