import { useParams } from "@remix-run/react"
import SupplierOOSDashboard from "../components/controlKpi/supplier-oos-dashboard"

// Supplier data
const supplierAlertsData = [
  {
    supplierName: "Stanley Black & Decker",
    supplierCode: "SBD-001",
    componentType: "CRAFTSMAN Power Tools",
    materialCode: "CRAFT-DRILL-20V",
    alertType: "Critical OOS",
    affectedSKUs: 5,
    estimatedImpact: 1850000,
    currentStock: 320,
    requiredStock: 8500,
    shortagePercentage: 96.2,
    supplierStatus: "Production Halt",
    estimatedRecovery: "10-14 days",
    priority: "Critical",
    dueDate: "01/20/2025",
    location: "New Britain, CT",
    contractValue: 125000000,
    qualityRating: 4.7,
    onTimeDelivery: 94.2,
  },
  {
    supplierName: "Whirlpool Corporation",
    supplierCode: "WHP-002",
    componentType: "Refrigerators & Appliances",
    materialCode: "WHP-REF-25CF",
    alertType: "Severe OOS",
    affectedSKUs: 3,
    estimatedImpact: 2950000,
    currentStock: 850,
    requiredStock: 6200,
    shortagePercentage: 86.3,
    supplierStatus: "Capacity Issues",
    estimatedRecovery: "7-10 days",
    priority: "High",
    dueDate: "01/22/2025",
    location: "Benton Harbor, MI",
    contractValue: 180000000,
    qualityRating: 4.8,
    onTimeDelivery: 91.5,
  },
  {
    supplierName: "Husqvarna Group",
    supplierCode: "HUS-003",
    componentType: "Riding Mowers & Equipment",
    materialCode: "HUS-MOWER-42IN",
    alertType: "Critical OOS",
    affectedSKUs: 4,
    estimatedImpact: 3200000,
    currentStock: 125,
    requiredStock: 4500,
    shortagePercentage: 97.2,
    supplierStatus: "Supply Chain Disruption",
    estimatedRecovery: "14-21 days",
    priority: "Critical",
    dueDate: "01/18/2025",
    location: "Charlotte, NC",
    contractValue: 95000000,
    qualityRating: 4.6,
    onTimeDelivery: 89.8,
  },
  {
    supplierName: "Mohawk Industries",
    supplierCode: "MOH-004",
    componentType: "Pergo Laminate Flooring",
    materialCode: "PERGO-OAK-8MM",
    alertType: "Moderate OOS",
    affectedSKUs: 6,
    estimatedImpact: 1250000,
    currentStock: 2400,
    requiredStock: 4800,
    shortagePercentage: 50.0,
    supplierStatus: "Partial Production",
    estimatedRecovery: "5-7 days",
    priority: "Medium",
    dueDate: "01/25/2025",
    location: "Calhoun, GA",
    contractValue: 75000000,
    qualityRating: 4.5,
    onTimeDelivery: 92.1,
  },
  {
    supplierName: "Suncast Corporation",
    supplierCode: "SUN-005",
    componentType: "Storage Sheds & Outdoor",
    materialCode: "SUN-SHED-10X12",
    alertType: "Severe OOS",
    affectedSKUs: 2,
    estimatedImpact: 980000,
    currentStock: 180,
    requiredStock: 2200,
    shortagePercentage: 91.8,
    supplierStatus: "Quality Issues",
    estimatedRecovery: "12-16 days",
    priority: "High",
    dueDate: "01/19/2025",
    location: "Batavia, IL",
    contractValue: 45000000,
    qualityRating: 4.3,
    onTimeDelivery: 87.6,
  },
  {
    supplierName: "LG Electronics USA",
    supplierCode: "LGE-006",
    componentType: "Washer/Dryer Sets",
    materialCode: "LG-WASH-FRONT",
    alertType: "Critical OOS",
    affectedSKUs: 3,
    estimatedImpact: 2100000,
    currentStock: 95,
    requiredStock: 3200,
    shortagePercentage: 97.0,
    supplierStatus: "Equipment Failure",
    estimatedRecovery: "10-14 days",
    priority: "Critical",
    dueDate: "01/17/2025",
    location: "Clarksville, TN",
    contractValue: 140000000,
    qualityRating: 4.7,
    onTimeDelivery: 93.4,
  },
  {
    supplierName: "MasterBrand Cabinets",
    supplierCode: "MBC-007",
    componentType: "Diamond NOW Cabinets",
    materialCode: "DIAM-KIT-SHAKER",
    alertType: "Moderate OOS",
    affectedSKUs: 4,
    estimatedImpact: 1680000,
    currentStock: 1650,
    requiredStock: 2800,
    shortagePercentage: 41.1,
    supplierStatus: "Raw Material Delay",
    estimatedRecovery: "6-8 days",
    priority: "Medium",
    dueDate: "01/26/2025",
    location: "Jasper, IN",
    contractValue: 85000000,
    qualityRating: 4.4,
    onTimeDelivery: 88.9,
  },
  {
    supplierName: "DEWALT (Stanley Black & Decker)",
    supplierCode: "DEW-008",
    componentType: "Professional Power Tools",
    materialCode: "DEW-SAW-MITER",
    alertType: "Severe OOS",
    affectedSKUs: 3,
    estimatedImpact: 1920000,
    currentStock: 420,
    requiredStock: 3100,
    shortagePercentage: 86.5,
    supplierStatus: "Workforce Shortage",
    estimatedRecovery: "8-12 days",
    priority: "High",
    dueDate: "01/21/2025",
    location: "Towson, MD",
    contractValue: 110000000,
    qualityRating: 4.8,
    onTimeDelivery: 92.7,
  },
]

// Mock function to get supplier data based on slug
function getSupplierData(slug: string) {
  return (
    supplierAlertsData.find((item) => slug.includes(encodeURIComponent(item.supplierCode))) || supplierAlertsData[0]
  )
}

export default function SupplierOOSDetailPage() {
  const params = useParams()
  const slug = params.supplierId || ''
  const supplierData = getSupplierData(slug)

  return <SupplierOOSDashboard supplierData={supplierData} />
}
