import DemandBalancingDashboard from "../components/controlKpi/demand/demand-balancing-dashboard"

function getDemandBalancingData(slug: string) {
    
  const demandBalancingData = [
    {
      sourceLocation: "META-CA-01",
      materialCode: "VR-Q3-128",
      revenueImpact: 4291328,
      unitImpact: 199597,
      impactCoverage: 100.0,
      confidenceLevel: 81.21,
      predictedAction: "Transfer",
      actionPriority: "High",
      dueDate: "01/18/2025",
      description: "Transfer 5,500 units of Quest 3 128GB to META-TX-01 DC to fill projected backorders",
      alertType: "Stock Shortage",
      transferLeadTime: "3-5 days",
      currentStock: 12450,
      projectedDemand: 18000,
    },
    {
      sourceLocation: "META-EU-01",
      materialCode: "VR-Q3-512",
      revenueImpact: 3306994,
      unitImpact: 459010,
      impactCoverage: 100.0,
      confidenceLevel: 88.6,
      predictedAction: "Expedite",
      actionPriority: "High",
      dueDate: "01/20/2025",
      description: "Expedite existing stock transfer of 459,010 units of Quest 3 512GB to META-APAC-01 DC",
      alertType: "Critical Shortage",
      transferLeadTime: "7-10 days",
      currentStock: 8920,
      projectedDemand: 15200,
    },
    {
      sourceLocation: "META-TX-01",
      materialCode: "VR-PRO-256",
      revenueImpact: 2999437,
      unitImpact: 139185,
      impactCoverage: 100.0,
      confidenceLevel: 85.06,
      predictedAction: "Transfer",
      actionPriority: "High",
      dueDate: "01/19/2025",
      description: "Transfer 139,185 units of Quest Pro to META-NJ-01 DC to fill projected backorders",
      alertType: "Stock Shortage",
      transferLeadTime: "2-4 days",
      currentStock: 2340,
      projectedDemand: 8500,
    },
    {
      sourceLocation: "META-CA-01",
      materialCode: "VR-PRO-256",
      revenueImpact: 2029513,
      unitImpact: 96277,
      impactCoverage: 100.0,
      confidenceLevel: 85.06,
      predictedAction: "Transfer",
      actionPriority: "Medium",
      dueDate: "01/22/2025",
      description: "Transfer 96,277 units of Quest Pro to META-UK-01 DC to fill projected backorders",
      alertType: "Low Stock",
      transferLeadTime: "5-7 days",
      currentStock: 1890,
      projectedDemand: 4200,
    },
    {
      sourceLocation: "META-APAC-01",
      materialCode: "VR-Q3-128",
      revenueImpact: 1937593,
      unitImpact: 193480,
      impactCoverage: 100.0,
      confidenceLevel: 82.27,
      predictedAction: "Expedite",
      actionPriority: "High",
      dueDate: "01/21/2025",
      description: "Expedite existing stock transfer of 193,480 units of Quest 3 128GB to META-CA-01 DC",
      alertType: "Stock Shortage",
      transferLeadTime: "8-12 days",
      currentStock: 4560,
      projectedDemand: 9200,
    },
    {
      sourceLocation: "META-EU-01",
      materialCode: "VR-Q3-BUNDLE",
      revenueImpact: 1850740,
      unitImpact: 191730,
      impactCoverage: 100.0,
      confidenceLevel: 80.07,
      predictedAction: "Transfer",
      actionPriority: "Medium",
      dueDate: "01/25/2025",
      description: "Transfer 191,730 units of Quest 3 Elite Bundle to META-CA-01 DC to fill projected backorders",
      alertType: "Optimal Stock",
      transferLeadTime: "6-8 days",
      currentStock: 3420,
      projectedDemand: 4500,
    },
    {
      sourceLocation: "META-APAC-01",
      materialCode: "VR-Q3-512",
      revenueImpact: 1727740,
      unitImpact: 225300,
      impactCoverage: 100.0,
      confidenceLevel: 86.55,
      predictedAction: "Manufacture",
      actionPriority: "High",
      dueDate: "01/23/2025",
      description: "Manufacture additional 225,300 units of Quest 3 512GB to fill projected backorders",
      alertType: "Critical Shortage",
      transferLeadTime: "14-21 days",
      currentStock: 890,
      projectedDemand: 12000,
    },
    {
      sourceLocation: "META-TX-01",
      materialCode: "VR-Q3-128",
      revenueImpact: 1450534,
      unitImpact: 134558,
      impactCoverage: 100.0,
      confidenceLevel: 87.09,
      predictedAction: "Transfer",
      actionPriority: "Medium",
      dueDate: "01/24/2025",
      description: "Transfer 134,558 units of Quest 3 128GB to META-EU-01 DC to fill projected backorders",
      alertType: "Low Stock",
      transferLeadTime: "4-6 days",
      currentStock: 7240,
      projectedDemand: 6800,
    },
  ]
  // Find matching item based on slug
  return (
    demandBalancingData.find((item) => slug.includes(encodeURIComponent(item.materialCode))) || demandBalancingData[0]
  )
}

export default async function DemandBalancingDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const resolvedParams = await params
  const { slug } = resolvedParams
  const demandData = getDemandBalancingData(slug)

  return <DemandBalancingDashboard demandData={demandData} />
}
